# Generated by Django 5.2.13 on 2026-05-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_book_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='book',
            field=models.ManyToManyField(related_name='users', to='accounts.book'),
        ),
    ]
